import { createContext, useContext, useEffect, useState } from 'react'
import type { ReactNode } from 'react'

export type Language = 'zh' | 'en'

const storageKey = 'dumbbell-language'

const translations = {
  zh: {
    appName: '哑铃训练',
    subtitle: '图示详解',
    home: '首页',
    library: '动作库',
    favorites: '收藏',
    profile: '我的',
    selectBodyPart: '选择训练部位',
    recommended: '推荐动作',
    viewAll: '查看全部',
    chestTraining: '胸部训练',
    all: '全部',
    beginner: '入门',
    intermediate: '进阶',
    noEquipment: '无需器械',
    benchRequired: '需要训练凳',
    dumbbellsOnly: '哑铃',
    search: '搜索',
    searchPlaceholder: '搜索动作、部位、肌肉群...',
    recentSearches: '最近搜索',
    popularSearches: '热门搜索',
    searchResults: '搜索结果',
    myFavorites: '我的收藏',
    edit: '编辑',
    noFavorites: '还没有收藏动作',
    settings: '设置',
    darkMode: '深色模式',
    language: '语言',
    displaySettings: '显示设置',
    fontSize: '字体大小',
    clearCache: '清除缓存',
    backup: '数据备份与导出',
    about: '关于应用',
    terms: '使用条款',
    privacy: '隐私政策',
    startPosition: '起始姿势',
    endPosition: '结束姿势',
    targetMuscles: '目标肌肉',
    steps: '动作步骤',
    tips: '动作要点',
    mistakes: '常见错误',
    recommendation: '推荐',
    back: '返回',
    favorite: '收藏',
    favoriteAdded: '已收藏',
    favoriteRemoved: '已取消收藏',
    exerciseContent: '动作内容',
    exerciseGuide: '动作图解',
    trainingDetails: '训练要点',
    forceAnalysis: '发力解析',
    primaryMuscle: '主要肌群',
    supportingMuscles: '辅助肌群',
    keyPoints: '关键要点',
    trainingAdvice: '训练建议',
    fullMovement: '动作全程',
    formCheckpoints: '姿势要点',
    training: '训练',
    allExercises: '全部',
    noExercises: '该部位暂未收录动作',
  },
  en: {
    appName: 'Dumbbell Training',
    subtitle: 'Visual Exercise Guide',
    home: 'Home',
    library: 'Exercises',
    favorites: 'Favorites',
    profile: 'Profile',
    selectBodyPart: 'Choose a body part',
    recommended: 'Recommended',
    viewAll: 'View all',
    chestTraining: 'Chest Training',
    all: 'All',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    noEquipment: 'No equipment',
    benchRequired: 'Bench required',
    dumbbellsOnly: 'Dumbbell',
    search: 'Search',
    searchPlaceholder: 'Search exercises, body parts, muscles...',
    recentSearches: 'Recent searches',
    popularSearches: 'Popular searches',
    searchResults: 'Search results',
    myFavorites: 'My Favorites',
    edit: 'Edit',
    noFavorites: 'No exercises saved yet',
    settings: 'Settings',
    darkMode: 'Dark mode',
    language: 'Language',
    displaySettings: 'Display settings',
    fontSize: 'Font size',
    clearCache: 'Clear cache',
    backup: 'Backup & export',
    about: 'About',
    terms: 'Terms of use',
    privacy: 'Privacy policy',
    startPosition: 'Start position',
    endPosition: 'End position',
    targetMuscles: 'Target muscles',
    steps: 'Steps',
    tips: 'Form tips',
    mistakes: 'Common mistakes',
    recommendation: 'Recommendation',
    back: 'Back',
    favorite: 'Favorite',
    favoriteAdded: 'Added to favorites',
    favoriteRemoved: 'Removed from favorites',
    exerciseContent: 'Exercise content',
    exerciseGuide: 'Visual guide',
    trainingDetails: 'Training details',
    forceAnalysis: 'Muscle focus',
    primaryMuscle: 'Primary',
    supportingMuscles: 'Supporting',
    keyPoints: 'Key points',
    trainingAdvice: 'Training advice',
    fullMovement: 'Full movement',
    formCheckpoints: 'Form checkpoints',
    training: ' Training',
    allExercises: 'All',
    noExercises: 'No exercises have been added for this body part yet',
  },
} as const

const exerciseText: Record<string, string> = {
  俯身飞鸟: 'Bent-Over Reverse Fly',
  胸部: 'Chest',
  背部: 'Back',
  肩部: 'Shoulders',
  手臂: 'Arms',
  腿部: 'Legs',
  臀部: 'Glutes',
  核心: 'Core',
  全身: 'Full Body',
  三角肌后束: 'Rear Deltoid',
  菱形肌: 'Rhomboids',
  斜方肌中束: 'Middle trapezius',
  肩后束: 'Rear delts',
  哑铃: 'Dumbbell',
  起始站姿: 'Start stance',
  俯身准备: 'Hinge setup',
  打开: 'Open',
  还原: 'Return',
  '核心收紧，胸部打开，哑铃自然下垂':
    'Brace your core, open your chest, and let the dumbbells hang naturally.',
  '髋部后折，膝盖微屈，背部保持平直':
    'Hinge at the hips, soften your knees, and keep your back flat.',
  '肩胛先动，肩后束带动手臂向两侧展开':
    'Lead with the shoulder blades and let the rear delts open the arms.',
  '保持躯干稳定，缓慢下放并持续保持张力':
    'Keep the torso steady, lower slowly, and maintain tension.',
  保持中立脊柱: 'Keep a neutral spine',
  '全程背部平直，核心收紧，避免弓背或塌腰':
    'Keep your back flat and core braced without rounding or overextending.',
  肩胛稳定后收: 'Retract stable shoulder blades',
  '肩膀下沉，肩胛骨稳定，顶峰更好孤立后肩':
    'Keep the shoulders down and blades stable to isolate the rear delts at the top.',
  肘部微屈固定: 'Keep a fixed soft elbow',
  '肘部角度全程不变，减少小臂和关节代偿':
    'Keep the elbow angle unchanged to reduce forearm and joint compensation.',
  '肩后束 · 上背部': 'Rear delts · Upper back',
  '顶峰稍停，感受目标肌肉发力，控制节奏':
    'Pause briefly at the top, feel the target muscles, and control the tempo.',
  站稳: 'Set stance',
  俯身: 'Hinge',
  核心收紧: 'Brace core',
  髋部后折: 'Hinge hips',
  肩胛先动: 'Lead with shoulder blades',
  缓慢下放: 'Lower slowly',
  '胸部打开，颈部自然': 'Open the chest and keep the neck neutral',
  '膝盖微屈，背部平直': 'Soften the knees and keep the back flat',
  肩后束带动手臂展开: 'Let the rear delts drive the arms open',
  保持躯干稳定与张力: 'Keep the torso steady and maintain tension',
  俯身飞鸟顶峰收缩与肩后束发力示意: 'Bent-over reverse fly peak contraction and rear-delt focus',
  双手持哑铃自然站立: 'Stand naturally with a dumbbell in each hand',
  髋部后折进入俯身姿势: 'Hinge at the hips into the bent-over position',
  俯身姿势向两侧打开哑铃: 'Open the dumbbells to both sides from the hinged position',
  控制哑铃回到起始位置: 'Control the dumbbells back to the starting position',
  '肩胛先稳定后收，再带动双臂向两侧展开。':
    'Stabilize and retract the shoulder blades before opening both arms.',
  '肩膀下沉，颈部放松': 'Keep the shoulders down and neck relaxed',
  肩胛骨向脊柱靠拢: 'Draw the shoulder blades toward the spine',
  肘部微屈并保持固定: 'Keep a fixed soft bend in the elbows',
  背部中立: 'Neutral back',
  肩膀下沉: 'Shoulders down',
  肘部微屈: 'Soft elbows',
  控制节奏: 'Control the tempo',
  '髋部折叠，脊柱保持自然直线': 'Hinge at the hips and keep a naturally straight spine',
  '远离耳朵，肩胛稳定后收': 'Keep the shoulders away from the ears and retract with control',
  '固定角度，不要甩动小臂': 'Fix the elbow angle without swinging the forearms',
  '打开1秒 · 停1秒 · 回落2秒': 'Open 1 sec · pause 1 sec · lower 2 sec',
  斜方肌抢先发力: 'The upper traps take over',
  主动下沉肩膀: 'Actively lower the shoulders',
  下背弯曲: 'Rounded lower back',
  脊柱失去中立: 'The spine loses its neutral position',
  核心收紧并减重: 'Brace the core and reduce the load',
  重量过大: 'Too much weight',
  身体借力甩动: 'The body swings for momentum',
  全程保持可控: 'Keep every phase controlled',
  组数: 'Sets',
  次数: 'Reps',
  休息: 'Rest',
  '60–90秒': '60–90 sec',
  '双脚与髋同宽站立，核心收紧，胸部打开，哑铃自然下垂。':
    'Stand hip-width apart, brace your core, open your chest, and let the dumbbells hang naturally.',
  '髋部后折，身体前倾，膝盖微屈，保持背部自然中立。':
    'Hinge at the hips with a soft bend in the knees and keep your back naturally neutral.',
  '肩胛先稳定后收，手肘保持微屈，双臂向身体两侧打开。':
    'Stabilize and retract the shoulder blades, keep soft elbows, and open both arms to the sides.',
  '保持躯干稳定，缓慢控制哑铃回落，回到起始位置前仍保持张力。':
    'Keep the torso steady and lower with control, maintaining tension before the next rep.',
  全程保持背部自然中立: 'Keep a naturally neutral back throughout',
  '肩膀下沉，肩胛骨稳定后收': 'Keep the shoulders down and shoulder blades stable',
  手肘全程微屈且角度不变: 'Keep a fixed soft bend in the elbows',
  '选择可控制的轻重量，用肩后束而非摆动躯干发力':
    'Choose a controllable light load and use the rear delts instead of swinging the torso',
  耸肩代偿: 'Shrugging to compensate',
  下背部弯曲: 'Rounding the lower back',
  重量过大导致动作变形: 'Using too much weight and losing form',
  '2–3组': '2–3 sets',
  '12–15次': '12–15 reps',
  '休息60–90秒': 'Rest 60–90 sec',
  单臂哑铃划船: 'One-Arm Dumbbell Row',
  背阔肌: 'Lats',
  肱二头肌: 'Biceps',
  支撑站姿: 'Supported stance',
  拉向髋部: 'Row to hip',
  控制下放: 'Controlled lower',
  '前后站稳，左手支撑左腿': 'Set a split stance and brace your left hand on your left thigh.',
  '髋部后折，右臂自然下垂': 'Hinge at the hips and let the right arm hang naturally.',
  '肩胛后收，手肘贴近身体': 'Retract the shoulder blade and keep the elbow close.',
  '躯干不转，沿原轨迹还原': 'Keep the torso square and return along the same path.',
  保持背部中立: 'Keep a neutral back',
  '髋部折叠，核心收紧，避免弓背或塌腰':
    'Hinge at the hips, brace the core, and avoid rounding or overextending.',
  '肩膀下沉，先稳定肩胛再拉起哑铃': 'Keep the shoulder down and stabilize the blade before rowing.',
  手肘拉向髋部: 'Drive the elbow toward the hip',
  '手肘贴近身体，不要向外张开': 'Keep the elbow close instead of flaring it out.',
  '背阔肌 · 中背部': 'Lats · Mid back',
  '顶峰稍停，躯干保持稳定，感受背部收缩':
    'Pause at the top, keep the torso steady, and feel the back contract.',
  单臂哑铃划船顶峰收缩与背阔肌发力示意: 'One-arm dumbbell row peak contraction and lat focus',
  '肩胛先稳定后收，手肘贴身拉向髋部。':
    'Stabilize and retract the shoulder blade, then drive the elbow close toward the hip.',
  '支撑手稳定，肩膀下沉': 'Keep the support hand firm and the shoulder down',
  '背部中立，髋部保持正对': 'Keep a neutral back with the hips square',
  手肘贴身拉向髋部: 'Drive the elbow close toward the hip',
  支撑: 'Brace',
  站距稳定: 'Stable stance',
  左手压稳左侧大腿: 'Brace the left hand firmly on the left thigh',
  前后站立并以左手支撑左腿: 'Use a split stance and brace the left hand on the left leg',
  哑铃垂在肩膀下方: 'Let the dumbbell hang below the shoulder',
  背部保持中立让右臂自然下垂: 'Keep a neutral back and let the right arm hang naturally',
  拉起: 'Row',
  手肘贴身: 'Elbow close',
  沿身体拉向髋部: 'Row close to the body toward the hip',
  右手肘贴近身体拉起哑铃: 'Row the dumbbell with the right elbow close to the body',
  下放: 'Lower',
  缓慢还原: 'Return slowly',
  '躯干不转，肩膀不耸': 'Keep the torso square and avoid shrugging',
  控制哑铃沿原轨迹缓慢下放: 'Lower the dumbbell slowly along the same path',
  肩胛稳定: 'Stable shoulder blade',
  '肩膀下沉，先稳定再向后收': 'Keep the shoulder down, stabilize, then retract',
  肘向髋部: 'Elbow to hip',
  '拉起1秒 · 停1秒 · 下放2秒': 'Row 1 sec · pause 1 sec · lower 2 sec',
  肩膀主动远离耳朵: 'Actively move the shoulder away from the ear',
  躯干旋转: 'Torso rotation',
  髋部跟随打开: 'The hips rotate open with the pull',
  核心收紧保持正对: 'Brace the core and keep the hips square',
  手臂借力猛拉: 'The arm jerks the weight with momentum',
  减轻重量慢速完成: 'Reduce the load and move slowly',
  '双脚前后站稳，左手撑住左腿，右手握住哑铃。':
    'Set a stable split stance, brace the left hand on the left leg, and hold the dumbbell in the right hand.',
  '髋部后折进入俯身，背部保持自然中立，右臂垂在肩膀下方。':
    'Hinge forward with a naturally neutral back and let the right arm hang below the shoulder.',
  '肩胛先稳定后收，右手肘贴近身体并拉向髋部。':
    'Stabilize and retract the shoulder blade, keeping the right elbow close as it moves toward the hip.',
  '保持躯干和髋部稳定，缓慢下放哑铃至手臂自然伸展。':
    'Keep the torso and hips steady while lowering until the arm naturally extends.',
  支撑手稳定压住大腿: 'Brace the support hand firmly on the thigh',
  '背部保持自然中立，髋部不要转动': 'Keep a naturally neutral back without rotating the hips',
  手肘贴近身体并拉向髋部: 'Keep the elbow close and drive it toward the hip',
  '选择可控重量，避免借力扭转躯干': 'Use a controllable load without twisting for momentum',
  重量过大导致手臂猛拉: 'Using too much weight and jerking with the arm',
  '3组': '3 sets',
  '每侧10–12次': '10–12 reps per side',
  哑铃罗马尼亚硬拉: 'Dumbbell Romanian Deadlift',
  腘绳肌: 'Hamstrings',
  臀大肌: 'Gluteus maximus',
  竖脊肌: 'Erector spinae',
  站稳持铃: 'Set stance',
  髋部后移: 'Hips back',
  下放拉伸: 'Lower and stretch',
  站直还原: 'Stand and return',
  '双脚与髋同宽，哑铃贴近大腿': 'Stand hip-width apart with the dumbbells close to the thighs.',
  '膝盖微屈，背部保持自然中立': 'Keep soft knees and a naturally neutral back.',
  '哑铃贴腿，感受大腿后侧拉伸': 'Keep the dumbbells close and feel the hamstrings stretch.',
  '臀腿发力，髋部向前回到站姿':
    'Use the glutes and hamstrings to bring the hips forward and stand.',
  '躯干随髋部前倾，避免弓背或塌腰':
    'Let the torso follow the hip hinge without rounding or overextending.',
  髋部主动后移: 'Drive the hips back',
  '想象臀部向后触碰墙面，不要主动下蹲':
    'Imagine reaching the hips toward a wall instead of squatting down.',
  哑铃贴近双腿: 'Keep dumbbells close to the legs',
  '手臂自然垂直，哑铃沿腿部上下移动':
    'Let the arms hang vertically and move the dumbbells along the legs.',
  '腘绳肌 · 臀部': 'Hamstrings · Glutes',
  '下放感受拉伸，站起感受臀腿收缩':
    'Feel the stretch while lowering and the glutes and hamstrings contract as you stand.',
  哑铃罗马尼亚硬拉底部姿势与臀腿后侧发力示意:
    'Dumbbell Romanian deadlift bottom position and posterior-chain focus',
  '髋部向后移动，哑铃贴腿下放，再由臀腿带动站起。':
    'Push the hips back, lower the dumbbells close to the legs, then stand using the glutes and hamstrings.',
  '背部自然中立，颈部放松': 'Keep a naturally neutral back and relaxed neck',
  '髋部向后，膝盖保持微屈': 'Push the hips back and keep the knees softly bent',
  '哑铃贴腿，下放至小腿中段': 'Keep the dumbbells close and lower to mid-shin',
  双脚髋宽: 'Feet hip-width',
  哑铃贴近大腿前侧: 'Keep the dumbbells close to the front of the thighs',
  双脚与髋同宽持哑铃自然站立: 'Stand naturally with dumbbells and feet hip-width apart',
  后移: 'Hinge back',
  髋部主导: 'Lead with hips',
  '膝盖微屈，臀部向后': 'Soften the knees and push the hips back',
  保持背部中立并将髋部向后移动: 'Keep a neutral back while moving the hips backward',
  哑铃贴腿: 'Dumbbells close',
  下放至小腿中段: 'Lower to mid-shin',
  哑铃贴近双腿下放至小腿中段: 'Lower the dumbbells close to the legs to mid-shin',
  站起: 'Stand',
  臀腿发力: 'Drive with glutes and hamstrings',
  '髋部向前，站直不后仰': 'Bring the hips forward and stand tall without leaning back',
  臀腿发力带动身体回到站姿: 'Use the glutes and hamstrings to return to standing',
  '核心收紧，脊柱保持自然直线': 'Brace the core and keep a naturally straight spine',
  '臀部向后，不要主动向下蹲': 'Push the hips back instead of actively squatting down',
  '手臂垂直，重量靠近身体': 'Keep the arms vertical and the weight close to the body',
  '下放2秒 · 停1秒 · 站起1秒': 'Lower 2 sec · pause 1 sec · stand 1 sec',
  弓背下放: 'Rounding while lowering',
  脊柱失去自然中立: 'The spine loses its natural neutral position',
  减小幅度并收紧核心: 'Reduce the range and brace the core',
  下蹲过多: 'Squatting too much',
  膝盖过度向前移动: 'The knees travel too far forward',
  髋部主动向后移动: 'Actively move the hips backward',
  哑铃离腿: 'Dumbbells drift away',
  重量远离身体重心: 'The weight moves away from the body',
  沿双腿贴近上下移动: 'Move the dumbbells close along the legs',
  '双脚与髋同宽站立，双手持哑铃贴近大腿前侧。':
    'Stand hip-width apart with both dumbbells close to the front of the thighs.',
  '膝盖保持微屈，髋部向后移动，背部保持自然中立。':
    'Keep the knees softly bent, move the hips back, and maintain a naturally neutral back.',
  '哑铃贴腿下放至小腿中段，感受大腿后侧拉伸。':
    'Lower the dumbbells close to the legs to mid-shin and feel the hamstrings stretch.',
  '脚掌踩稳，臀腿发力带动髋部向前，站直后不要后仰。':
    'Keep the feet planted and use the glutes and hamstrings to stand without leaning back.',
  '动作由髋部后移主导，不要主动下蹲': 'Lead with the hips moving back instead of squatting down',
  哑铃始终贴近双腿移动: 'Keep the dumbbells close to the legs throughout',
  下放至背部仍能保持自然中立的位置:
    'Lower only as far as you can maintain a naturally neutral back',
  '使用可控重量，站起时不要过度后仰': 'Use a controllable load and avoid leaning back at the top',
  屈膝过多变成深蹲: 'Bending the knees too much and turning it into a squat',
  哑铃远离双腿: 'Letting the dumbbells drift away from the legs',
  '10–12次': '10–12 reps',
  高脚杯深蹲: 'Goblet Squat',
  股四头肌: 'Quadriceps',
  内收肌: 'Adductors',
  持铃站稳: 'Set stance',
  控制下蹲: 'Controlled descent',
  底部稳定: 'Stable bottom',
  蹬地站起: 'Drive to stand',
  '双脚略宽，哑铃贴近胸前': 'Set the feet slightly wide and keep the dumbbell close to the chest.',
  '屈髋屈膝，膝盖跟随脚尖': 'Bend the hips and knees while tracking the knees with the toes.',
  '脚掌踩稳，背部保持自然中立': 'Keep the feet planted and the back naturally neutral.',
  '臀腿发力，膝盖保持对齐': 'Use the glutes and legs while keeping the knees aligned.',
  '胸部自然打开，避免弓背或过度前倾':
    'Keep the chest naturally open without rounding or leaning too far forward.',
  哑铃贴近胸前: 'Keep the dumbbell close to the chest',
  '双手稳定持铃，肘部自然朝向下方': 'Hold the dumbbell steadily with the elbows pointing down.',
  膝盖跟随脚尖: 'Track the knees with the toes',
  '膝盖稳定向外，不要出现内扣': 'Keep the knees tracking outward without collapsing inward.',
  '股四头肌 · 臀部': 'Quadriceps · Glutes',
  '下蹲保持控制，站起时臀腿共同发力':
    'Stay controlled on the way down and use the glutes and legs to stand.',
  高脚杯深蹲底部姿势与股四头肌臀部发力示意:
    'Goblet squat bottom position with quadriceps and glute focus',
  '哑铃贴近胸前，膝盖跟随脚尖，下蹲后由臀腿带动站起。':
    'Keep the dumbbell close, track the knees with the toes, and use the glutes and legs to stand.',
  '哑铃贴近胸前，肘部向下': 'Keep the dumbbell close with the elbows pointing down',
  '背部自然中立，胸部打开': 'Keep a naturally neutral back and open chest',
  '膝盖跟随脚尖，脚掌踩稳': 'Track the knees with the toes and keep the feet planted',
  持铃贴胸: 'Dumbbell at chest',
  '双脚略宽，脚尖微外': 'Set the feet slightly wide with the toes turned out',
  双手将一只哑铃竖直贴近胸前站立: 'Stand with one dumbbell held vertically close to the chest',
  下蹲: 'Descend',
  膝髋同屈: 'Bend hips and knees',
  膝盖跟随脚尖方向: 'Track the knees in the direction of the toes',
  保持哑铃贴胸并控制身体向下蹲:
    'Keep the dumbbell close to the chest while descending with control',
  底部: 'Bottom',
  脚掌踩稳: 'Feet planted',
  '背部中立，膝盖不内扣': 'Keep a neutral back and prevent the knees from collapsing in',
  高脚杯深蹲底部保持脚掌着地: 'Keep the whole foot planted at the bottom of the goblet squat',
  蹬地发力: 'Push the floor',
  臀腿发力回到站姿: 'Use the glutes and legs to return to standing',
  脚掌蹬地带动身体站起: 'Push through the feet to stand',
  '核心收紧，胸部保持自然打开': 'Brace the core and keep the chest naturally open',
  '重量靠近身体，肘部自然向下': 'Keep the weight close with the elbows pointing down',
  膝盖对齐: 'Knees aligned',
  '膝盖跟随脚尖，不要向内扣': 'Track the knees with the toes without collapsing inward',
  '下蹲2秒 · 停1秒 · 站起1秒': 'Descend 2 sec · pause 1 sec · stand 1 sec',
  膝盖内扣: 'Knees collapsing inward',
  膝盖偏离脚尖方向: 'The knees drift away from the toe line',
  主动向脚尖方向打开: 'Actively track the knees toward the toes',
  脚跟抬起: 'Heels lifting',
  身体重心过度前移: 'The body weight shifts too far forward',
  全脚掌均匀踩稳: 'Keep the whole foot evenly planted',
  过度前倾: 'Leaning too far forward',
  哑铃远离身体重心: 'The dumbbell moves away from the body',
  持铃贴胸并减小深度: 'Keep the dumbbell close and reduce the depth',
  '双脚略宽于髋站立，脚尖微向外，双手将哑铃贴近胸前。':
    'Stand slightly wider than hip-width with the toes turned out and the dumbbell close to the chest.',
  '保持脚掌踩稳，屈髋屈膝下蹲，膝盖跟随脚尖方向。':
    'Keep the feet planted, bend the hips and knees, and track the knees with the toes.',
  '下蹲至可控深度，背部保持自然中立，膝盖不要向内扣。':
    'Descend to a controllable depth with a neutral back and knees tracking outward.',
  '脚掌均匀蹬地，臀腿发力站起，回到稳定站姿。':
    'Push evenly through the feet and use the glutes and legs to return to a stable stance.',
  '哑铃始终贴近胸前，肘部自然向下':
    'Keep the dumbbell close to the chest with the elbows pointing down',
  '膝盖与脚尖方向一致，不要向内扣':
    'Keep the knees aligned with the toes without collapsing inward',
  全程保持脚跟和前脚掌稳定着地: 'Keep the heels and forefeet planted throughout',
  '使用可控重量，下蹲深度以姿势稳定为准':
    'Use a controllable load and squat only as deep as stable form allows',
  膝盖向内扣: 'Letting the knees collapse inward',
  脚跟离地: 'Letting the heels lift',
  身体过度前倾: 'Leaning the torso too far forward',
  '10–15次': '10–15 reps',
  站姿哑铃推举: 'Standing Dumbbell Shoulder Press',
  三角肌前束: 'Front deltoid',
  三角肌中束: 'Lateral deltoid',
  肱三头肌: 'Triceps',
  举至肩侧: 'Raise to shoulders',
  向上推举: 'Press overhead',
  '双脚髋宽，核心与臀部收紧': 'Stand hip-width with the core and glutes braced.',
  '前臂垂直，手腕位于肘部上方': 'Keep the forearms vertical with wrists stacked over elbows.',
  '双手推至肩膀正上方，肋骨下沉': 'Press above the shoulders while keeping the ribs down.',
  '沿原轨迹回落，躯干保持稳定': 'Lower along the same path while keeping the torso steady.',
  保持躯干稳定: 'Keep the torso stable',
  '核心收紧，肋骨下沉，避免挺腰借力': 'Brace the core, keep the ribs down, and avoid leaning back.',
  肩胛自然上转: 'Natural upward scapular rotation',
  '推举时肩胛自然活动，不要强行下压':
    'Let the shoulder blades move naturally instead of forcing them down.',
  肘腕保持对齐: 'Keep elbows and wrists aligned',
  '三角肌 · 肱三头': 'Deltoids · Triceps',
  向上推举时肩部与手臂共同发力: 'Use the shoulders and arms together during the press.',
  站姿哑铃推举顶峰姿势与三角肌发力示意:
    'Standing dumbbell shoulder press peak position and deltoid focus',
  '保持躯干稳定，将哑铃垂直推至肩膀上方，再缓慢下放。':
    'Keep the torso steady, press vertically above the shoulders, then lower slowly.',
  '核心收紧，肋骨保持下沉': 'Brace the core and keep the ribs down',
  '前臂垂直，手腕保持中立': 'Keep the forearms vertical and wrists neutral',
  双手推至肩膀正上方: 'Press both hands directly above the shoulders',
  '双脚髋宽，哑铃自然下垂': 'Stand hip-width and let the dumbbells hang naturally',
  双手持哑铃自然站立准备推举: 'Stand naturally with dumbbells ready to press',
  架铃: 'Rack',
  前臂垂直: 'Forearms vertical',
  哑铃举至肩侧位置: 'Bring the dumbbells to shoulder level',
  哑铃位于肩侧且前臂保持垂直: 'Hold the dumbbells at shoulder level with vertical forearms',
  推起: 'Press',
  垂直推举: 'Press vertically',
  双手推至肩膀上方: 'Press both hands above the shoulders',
  站姿将两只哑铃推至头顶: 'Press both dumbbells overhead from standing',
  沿原轨迹回到肩侧: 'Return to shoulder level along the same path',
  控制两只哑铃缓慢下放至肩侧: 'Control both dumbbells slowly down to shoulder level',
  躯干稳定: 'Stable torso',
  '核心与臀部收紧，避免挺腰': 'Brace the core and glutes without leaning back',
  肩胛自然: 'Natural shoulder blades',
  随手臂上举自然向上转动: 'Let the shoulder blades rotate upward with the arms',
  肘腕对齐: 'Elbows and wrists aligned',
  '前臂垂直，手腕不要后折': 'Keep the forearms vertical without bending the wrists back',
  '推起1秒 · 停1秒 · 下放2秒': 'Press 1 sec · pause 1 sec · lower 2 sec',
  挺腰借力: 'Leaning back for momentum',
  '肋骨外翻，腰部过度伸展': 'The ribs flare and the lower back overextends',
  收紧核心并减轻重量: 'Brace the core and reduce the load',
  手腕后折: 'Wrists bent back',
  重量偏离前臂支撑线: 'The weight shifts away from the forearm support line',
  保持手腕位于肘部上方: 'Keep the wrists stacked over the elbows',
  哑铃相碰: 'Dumbbells touching',
  顶端动作失去控制: 'Control is lost at the top',
  保持间距缓慢完成: 'Keep space between the dumbbells and move slowly',
  '双脚与髋同宽站立，两手持哑铃，核心与臀部轻收紧。':
    'Stand hip-width with dumbbells in both hands and lightly brace the core and glutes.',
  '将哑铃举至肩侧，前臂保持垂直，手腕位于肘部上方。':
    'Bring the dumbbells to shoulder level with vertical forearms and wrists over elbows.',
  '向上推举至双手位于肩膀上方，保持肋骨下沉且不挺腰。':
    'Press above the shoulders while keeping the ribs down without leaning back.',
  '控制哑铃沿原轨迹下放至肩侧，全程保持躯干稳定。':
    'Lower the dumbbells to shoulder level along the same path while keeping the torso steady.',
  '脚掌踩稳，核心与臀部保持收紧': 'Keep the feet planted and the core and glutes braced',
  '前臂保持垂直，手腕不要向后折': 'Keep the forearms vertical without bending the wrists back',
  '哑铃向肩膀正上方推举，顶端不要相碰':
    'Press directly above the shoulders without touching the dumbbells at the top',
  '使用可控重量，肩部出现锐痛时立即停止':
    'Use a controllable load and stop if you feel sharp shoulder pain',
  手腕向后折: 'Bending the wrists backward',
  顶端哑铃相碰: 'Letting the dumbbells touch at the top',
  '8–12次': '8–12 reps',
}

type TranslationKey = keyof typeof translations.zh
type LanguageValue = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: TranslationKey) => string
  text: (value: string) => string
}
const LanguageContext = createContext<LanguageValue | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(
    () => (localStorage.getItem(storageKey) as Language) || 'zh',
  )
  useEffect(() => {
    localStorage.setItem(storageKey, language)
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'
  }, [language])
  const t = (key: TranslationKey) => translations[language][key]
  const text = (value: string) => (language === 'en' ? exerciseText[value] || value : value)
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, text }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}
